/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iotsimulator.GUI;

import iotsimulator.Structure.Metric;

/**
 *
 * @author user
 */
public class SetupSensorDataDialog extends javax.swing.JDialog {

    CSVDataPanel cSVDataPanel;
    GeneratedDataPanel generatedDataPanel;
    
    MainFrame parent;
    
    /**
     * Creates new form SetupSensorDataDialog
     */
    public SetupSensorDataDialog(java.awt.Frame passed_parent, boolean modal) {
        super(passed_parent, modal);
        initComponents();
        parent=(MainFrame)passed_parent;
        initDataPanels(parent);
    }
    
    private void initDataPanels(MainFrame parent)
    {
        cSVDataPanel=new CSVDataPanel(parent);
        generatedDataPanel=new GeneratedDataPanel(parent);
        /**UNDER CONSTRUCTION
        * IT SHOULD REMEMBER THE PREVIOUS SESSION.
        */
        cSVFileRadioButtonActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cSVFileRadioButton = new javax.swing.JRadioButton();
        generatedDataRadioButton = new javax.swing.JRadioButton();
        confirmButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        buttonGroup1.add(cSVFileRadioButton);
        cSVFileRadioButton.setSelected(true);
        cSVFileRadioButton.setText("CSV file data");
        cSVFileRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSVFileRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cSVFileRadioButton);

        buttonGroup1.add(generatedDataRadioButton);
        generatedDataRadioButton.setText("Generated data");
        generatedDataRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatedDataRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(generatedDataRadioButton);

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        jPanel1.add(confirmButton);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1307, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cSVFileRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSVFileRadioButtonActionPerformed
        jPanel2.removeAll();
        jPanel2.add(cSVDataPanel);
        jPanel2.revalidate();
        jPanel2.repaint();
    }//GEN-LAST:event_cSVFileRadioButtonActionPerformed

    private void generatedDataRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatedDataRadioButtonActionPerformed
        jPanel2.removeAll();
        jPanel2.add(generatedDataPanel);
        jPanel2.revalidate();
        jPanel2.repaint();
    }//GEN-LAST:event_generatedDataRadioButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        if(cSVFileRadioButton.isSelected())
        {
            parent.iOTSimulator.metricManager.timeIndex=cSVDataPanel.jList1.getSelectedIndex();
            parent.iOTSimulator.metricManager.metricIndices=cSVDataPanel.jList2.getSelectedIndices();
            for(int i=0;i<cSVDataPanel.availableMetricIndices.length;i++)
            {
                parent.iOTSimulator.metricManager.availableMetrics.add(new Metric(cSVDataPanel.availableMetricIndices[i],cSVDataPanel.columns.get(cSVDataPanel.availableMetricIndices[i])));
            }
            for(int i=0;i<parent.iOTSimulator.metricManager.metricIndices.length;i++)
            {
                parent.iOTSimulator.metricManager.selectedMetrics.add(parent.iOTSimulator.metricManager.availableMetrics.get(i));
            }
            parent.iOTSimulator.metricManager.timeType=cSVDataPanel.buttonGroup1.getSelection().getActionCommand();
            parent.iOTSimulator.metricManager.smallestTimeScale=cSVDataPanel.buttonGroup2.getSelection().getActionCommand();
            
            parent.iOTSimulator.metricManager.customTimeFormat=cSVDataPanel.jTextField1.getText();
            
            parent.iOTSimulator.metricManager.setupTimeStamps();
            
        }else if(generatedDataRadioButton.isSelected()){
            parent.iOTSimulator.metricManager.timeIndex=0;
            parent.iOTSimulator.metricManager.metricIndices=generatedDataPanel.generatedMetricesIndices;
            parent.iOTSimulator.metricManager.availableMetrics.clear();
            parent.iOTSimulator.metricManager.selectedMetrics.clear();
            for(int i=0;i<generatedDataPanel.generatedMetricesIndices.length;i++)
            {
                parent.iOTSimulator.metricManager.availableMetrics.add(new Metric(generatedDataPanel.generatedMetricesIndices[i],generatedDataPanel.columns.get(generatedDataPanel.generatedMetricesIndices[i])));
                parent.iOTSimulator.metricManager.selectedMetrics.add(parent.iOTSimulator.metricManager.availableMetrics.get(parent.iOTSimulator.metricManager.availableMetrics.size()-1));
            }
            parent.iOTSimulator.metricManager.timeType="Raw number";
            parent.iOTSimulator.metricManager.smallestTimeScale="Miliseconds";
            parent.iOTSimulator.metricManager.setupTimeStamps();
            
        }
        
        this.setVisible(false);
    }//GEN-LAST:event_confirmButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cSVFileRadioButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JRadioButton generatedDataRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
