/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iotsimulator.GUI;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author user
 */
public class SetupSimulatorDialog extends javax.swing.JDialog {

    MainFrame parent;

    /**
     * Creates new form SimulatorSetupDialog
     */
    public SetupSimulatorDialog(java.awt.Frame passed_parent, boolean modal) {
        super(passed_parent, modal);
        initComponents();
        parent = (MainFrame) passed_parent;
        jFormattedTextField1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                warn();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                warn();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                warn();
            }

            public void warn() {
                int selectedMetric = jList1.getSelectedIndex();
                if (selectedMetric > -1) {
                    if (jFormattedTextField1.getText().length() > 0) {
                        parent.iOTSimulator.metricManager.selectedMetrics.get(selectedMetric).frequency = Long.valueOf(jFormattedTextField1.getText());
                    }
                }
            }
        });
        refreshDialog();
    }

    public void refreshDialog() {
        jSlider1.setValue(parent.iOTSimulator.timeController.simulationLengthPercentage);
        jSpinner1.setValue(parent.iOTSimulator.timeController.interpolationBufferSize);
        jSpinner2.setValue(parent.iOTSimulator.timeController.predictionBufferSize);
        fillPanel();
    }

    private void fillPanel() {
        jList1.setModel(new javax.swing.AbstractListModel() {
            @Override
            public int getSize() {
                return parent.iOTSimulator.metricManager.selectedMetrics.size();
            }

            @Override
            public Object getElementAt(int index) {
                return parent.iOTSimulator.metricManager.selectedMetrics.get(index).name;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Initial metric frequencies"));

        jLabel5.setText("Metric:");

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel6.setText("Frequency (in milliseconds):");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Duration of simultion (user defined smallest time scale):");

        jLabel4.setText("100%");

        jSlider1.setMinimum(1);
        jSlider1.setValue(100);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel2.setText("Prediction buffer size (number of records which affects storage use of devices):");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(50, 3, null, 1));

        jLabel3.setText("Interpolation buffer size (won't affect device memories, it's just an internal simulation parameter):");

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(40, 4, null, 1));

        jButton2.setText("Generate node-red model (depreciated)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Functionalities"));

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Signal emulation");
        jCheckBox1.setEnabled(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Reactive model");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Prediction");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Proactive model");
        jCheckBox4.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSpinner2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4))
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if (jList1.getSelectedIndex() > -1) {
            jFormattedTextField1.setText(String.valueOf(parent.iOTSimulator.metricManager.selectedMetrics.get(jList1.getSelectedIndex()).frequency));
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        jLabel4.setText(String.valueOf(jSlider1.getValue()));
    }//GEN-LAST:event_jSlider1StateChanged

    private void jFormattedTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField1KeyPressed
        try {
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                jFormattedTextField1.commitEdit();
                jPanel1.requestFocusInWindow();
            }
        } catch (ParseException ex) {
            Logger.getLogger(SetupSimulatorDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jFormattedTextField1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        parent.iOTSimulator.timeController.simulationLengthPercentage = (int) jSlider1.getValue();
        parent.iOTSimulator.timeController.predictionBufferSize = (int) jSpinner1.getValue();
        parent.iOTSimulator.timeController.interpolationBufferSize = (int) jSpinner2.getValue();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JSONArray finalFlow = new JSONArray();

        String rootDeviceRawString = new String();
        StringBuilder sb = new StringBuilder();
        try (BufferedReader br = Files.newBufferedReader(Paths.get("NodeRedGeneratedFlows/RootDevice.json"))) {

            // read line by line
            String line;
            while ((line = br.readLine()) != null) {
                sb.append(line).append("\n");
            }
            rootDeviceRawString = sb.toString();
        } catch (IOException e) {
            System.out.println("CAN'T READ ROOT DEVICE TEMPLATE JSON FILE");
        }

        String middleDeviceRawString = new String();
        sb = new StringBuilder();
        try (BufferedReader br = Files.newBufferedReader(Paths.get("NodeRedGeneratedFlows/MiddleDevice.json"))) {

            // read line by line
            String line;
            while ((line = br.readLine()) != null) {
                sb.append(line).append("\n");
            }
            middleDeviceRawString = sb.toString();
        } catch (IOException e) {
            System.out.println("CAN'T READ MIDDLE DEVICE TEMPLATE JSON FILE");
        }

        String endDeviceRawString = new String();
        sb = new StringBuilder();
        try (BufferedReader br = Files.newBufferedReader(Paths.get("NodeRedGeneratedFlows/EndDevice.json"))) {

            // read line by line
            String line;
            while ((line = br.readLine()) != null) {
                sb.append(line).append("\n");
            }
            endDeviceRawString = sb.toString();
        } catch (IOException e) {
            System.out.println("CAN'T READ END DEVICE TEMPLATE JSON FILE");
        }
        JSONArray rootJson = new JSONArray(rootDeviceRawString);
        JSONArray middleJson = new JSONArray(middleDeviceRawString);
        JSONArray endJson = new JSONArray(endDeviceRawString);

        for (int i = 0; i < parent.iOTSimulator.topologyDefinition.topology.topologyLevels.size(); i++) {
            if (i == 0) {
                for (int j = 0; j < parent.iOTSimulator.topologyDefinition.topology.topologyLevels.get(i).devices.size(); j++) {
                    JSONArray readySection = new JSONArray(rootJson.toString());
                    readySection.getJSONObject(0).put("label", parent.iOTSimulator.topologyDefinition.topology.topologyLevels.get(i).devices.get(j).name + j);
                    readySection.getJSONObject(0).put("id", parent.iOTSimulator.topologyDefinition.topology.topologyLevels.get(i).devices.get(j).name + j);
                    int outputLinkCounter = 0;
                    for (int k = 1; k < readySection.length(); k++) {
                        readySection.getJSONObject(k).put("z", readySection.getJSONObject(0).get("label"));
                        if (readySection.getJSONObject(k).getString("type").equals("link out")) {
                            String temporaryLinkName = readySection.getJSONObject(k).getString("id");
                            readySection.getJSONObject(k).put("id", readySection.getJSONObject(0).get("label") + "Output" + outputLinkCounter);
                            for (int m = 1; m < readySection.length(); m++) {
                                if (readySection.getJSONObject(m).has("wires")) {
                                    if (readySection.getJSONObject(m).getJSONArray("wires").length() > 0) {
                                        for (int h = 0; h < readySection.getJSONObject(m).getJSONArray("wires").getJSONArray(0).length(); h++) {
                                            if (readySection.getJSONObject(m).getJSONArray("wires").getJSONArray(0).getString(h).equals(temporaryLinkName)) {
                                                readySection.getJSONObject(m).getJSONArray("wires").getJSONArray(0).put(h, readySection.getJSONObject(0).get("label") + "Output" + outputLinkCounter);
                                            }
                                        }
                                    }
                                }
                            }
                            outputLinkCounter = outputLinkCounter + 1;
                        }
                    }
                    parent.iOTSimulator.topologyDefinition.topology.topologyLevels.get(i).devices.get(j).readyJson = readySection;
                    for(int g=0;g<readySection.length();g++)
                    {
                       finalFlow.put(readySection.get(g)); 
                    }
                }
            } else if (i == parent.iOTSimulator.topologyDefinition.topology.topologyLevels.size() - 1) {
                for (int j = 0; j < parent.iOTSimulator.topologyDefinition.topology.topologyLevels.get(i).devices.size(); j++) {
                    JSONArray readySection = new JSONArray(middleJson.toString());
                    readySection.getJSONObject(0).put("label", parent.iOTSimulator.topologyDefinition.topology.topologyLevels.get(i).devices.get(j).name + j);
                    readySection.getJSONObject(0).put("id", parent.iOTSimulator.topologyDefinition.topology.topologyLevels.get(i).devices.get(j).name + j);
                    int inputLinkCounter = 0;
                    int outputLinkCounter = 0;
                    for (int k = 1; k < readySection.length(); k++) {
                        readySection.getJSONObject(k).put("z", readySection.getJSONObject(0).get("label"));
                        if (readySection.getJSONObject(k).getString("type").equals("link in")) {
                            String temporaryLinkName = readySection.getJSONObject(k).getString("id");
                            readySection.getJSONObject(k).put("id", readySection.getJSONObject(0).get("label") + "Input" + inputLinkCounter);
                            for (int m = 1; m < readySection.length(); m++) {
                                if (readySection.getJSONObject(m).has("wires")) {
                                    if (readySection.getJSONObject(m).getJSONArray("wires").length() > 0) {
                                        for (int h = 0; h < readySection.getJSONObject(m).getJSONArray("wires").getJSONArray(0).length(); h++) {
                                            if (readySection.getJSONObject(m).getJSONArray("wires").getJSONArray(0).getString(h).equals(temporaryLinkName)) {
                                                readySection.getJSONObject(m).getJSONArray("wires").getJSONArray(0).put(h, readySection.getJSONObject(0).get("label") + "Input" + inputLinkCounter);
                                            }
                                        }
                                    }
                                }
                            }
                            inputLinkCounter = inputLinkCounter + 1;
                        }
                        if (readySection.getJSONObject(k).getString("type").equals("link out")) {
                            String temporaryLinkName = readySection.getJSONObject(k).getString("id");
                            readySection.getJSONObject(k).put("id", readySection.getJSONObject(0).get("label") + "Output" + outputLinkCounter);
                            for (int m = 1; m < readySection.length(); m++) {
                                if (readySection.getJSONObject(m).has("wires")) {
                                    if (readySection.getJSONObject(m).getJSONArray("wires").length() > 0) {
                                        for (int h = 0; h < readySection.getJSONObject(m).getJSONArray("wires").getJSONArray(0).length(); h++) {
                                            if (readySection.getJSONObject(m).getJSONArray("wires").getJSONArray(0).getString(h).equals(temporaryLinkName)) {
                                                readySection.getJSONObject(m).getJSONArray("wires").getJSONArray(0).put(h, readySection.getJSONObject(0).get("label") + "Output" + outputLinkCounter);
                                            }
                                        }
                                    }
                                }
                            }
                            outputLinkCounter = outputLinkCounter + 1;
                        }
                    }
                    parent.iOTSimulator.topologyDefinition.topology.topologyLevels.get(i).devices.get(j).readyJson = readySection;
                    for(int g=0;g<readySection.length();g++)
                    {
                       finalFlow.put(readySection.get(g)); 
                    }
                }
            } else {
                for (int j = 0; j < parent.iOTSimulator.topologyDefinition.topology.topologyLevels.get(i).devices.size(); j++) {
                    JSONArray readySection = new JSONArray(endJson.toString());
                    readySection.getJSONObject(0).put("label", parent.iOTSimulator.topologyDefinition.topology.topologyLevels.get(i).devices.get(j).name + j);
                    readySection.getJSONObject(0).put("id", parent.iOTSimulator.topologyDefinition.topology.topologyLevels.get(i).devices.get(j).name + j);
                    int inputLinkCounter = 0;
                    for (int k = 1; k < readySection.length(); k++) {
                        readySection.getJSONObject(k).put("z", readySection.getJSONObject(0).get("label"));
                        if (readySection.getJSONObject(k).getString("type").equals("link in")) {
                            String temporaryLinkName = readySection.getJSONObject(k).getString("id");
                            readySection.getJSONObject(k).put("id", readySection.getJSONObject(0).get("label") + "Input" + inputLinkCounter);
                            for (int m = 1; m < readySection.length(); m++) {
                                if (readySection.getJSONObject(m).has("wires")) {
                                    if (readySection.getJSONObject(m).getJSONArray("wires").length() > 0) {
                                        for (int h = 0; h < readySection.getJSONObject(m).getJSONArray("wires").getJSONArray(0).length(); h++) {
                                            if (readySection.getJSONObject(m).getJSONArray("wires").getJSONArray(0).getString(h).equals(temporaryLinkName)) {
                                                readySection.getJSONObject(m).getJSONArray("wires").getJSONArray(0).put(h, readySection.getJSONObject(0).get("label") + "Input" + inputLinkCounter);
                                            }
                                        }
                                    }
                                }
                            }
                            inputLinkCounter = inputLinkCounter + 1;
                        }
                    }
                    parent.iOTSimulator.topologyDefinition.topology.topologyLevels.get(i).devices.get(j).readyJson = readySection;
                    for(int g=0;g<readySection.length();g++)
                    {
                       finalFlow.put(readySection.get(g)); 
                    }
                }
            }
        }
        String str = finalFlow.toString(4).replace("\\", "");
        System.out.println(str);
        try {
            Files.write(Paths.get("./NodeRedGeneratedFlows/generatedModel.json"), str.getBytes());
        } catch (IOException ex) {
            Logger.getLogger(SetupSimulatorDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        parent.iOTSimulator.simulationOptions.isPredict=jCheckBox3.isSelected();
        if(jCheckBox3.isSelected()==true)
        {
            jCheckBox4.setEnabled(true);
        }else{
            parent.iOTSimulator.simulationOptions.isProactive=false;
            jCheckBox4.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        parent.iOTSimulator.simulationOptions.isReactive=jCheckBox2.isSelected();
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        parent.iOTSimulator.simulationOptions.isEmulate=jCheckBox1.isSelected();
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    // End of variables declaration//GEN-END:variables
}
